# Generated by Django 5.2.17 on 2026-10-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_alter_entreprise_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depot', models.DateField(auto_now=True)),
                ('statut', models.CharField(choices=[('DEPOSEE', 'Déposée'), ('RETENUE', 'Retenue'), ('REFUSEE', 'Refusée')], default='DEPOSEE', max_length=50)),
            ],
            options={
                'verbose_name': 'candidature',
                'verbose_name_plural': 'candidatures',
                'ordering': ['date_depot'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'competence',
                'verbose_name_plural': 'competences',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='EnseignantReferent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=10)),
            ],
            options={
                'verbose_name': 'enseignant',
                'verbose_name_plural': 'enseignants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=10)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('promotion', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'etudiant',
                'verbose_name_plural': 'etudiants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nb_places', models.PositiveBigIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'offre',
                'verbose_name_plural': 'offres',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='TuteurEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=10)),
            ],
            options={
                'verbose_name': 'tuteur',
                'verbose_name_plural': 'tuteurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.AddConstraint(
            model_name='entreprise',
            constraint=models.UniqueConstraint(fields=('nom', 'ville'), name='nom_par_ville'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='competences',
            field=models.ManyToManyField(related_name='etudiants', to='stages.competence'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='stages.etudiant'),
        ),
        migrations.AddField(
            model_name='offre',
            name='competences',
            field=models.ManyToManyField(related_name='offres', to='stages.competence'),
        ),
        migrations.AddField(
            model_name='offre',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres', to='stages.entreprise'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='stages.offre'),
        ),
        migrations.AddField(
            model_name='tuteurentreprise',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuteurs', to='stages.entreprise'),
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(fields=('etudiant', 'offre'), name='offre_par_etudiant'),
        ),
    ]
